config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'
  resources :recipes, except: [:index] do
    put :favorite, on: :member
  end
  resources :users, only: [:show]
  resources :kitchens, only: [:new, :create, :show]
  resources :food_types, only: [:new, :create, :show]
  resources :preferences, only: [:new, :create, :show]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ActiveRecord::Base
  belongs_to :recipe, counter_cache: :favorite_count
  belongs_to :user
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :recipe
  validates :name, presence: true
end

app/models/kitchen.rb
class Kitchen < ActiveRecord::Base
  has_many :recipe
  belongs_to :user
  validates :name, presence: true
  has_many :kitchens_user
  has_many :users, through: :kitchens_user, source: :user
end

app/models/kitchens_user.rb
class KitchensUser < ActiveRecord::Base
  belongs_to :kitchen
  belongs_to :user
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  has_many :recipe
  has_many :user
  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :kitchen
  belongs_to :food_type
  belongs_to :preference
  belongs_to :user
  validates :name, :kitchen_id, :food_type_id, :preference_id,
            :ingredients, :step_by_step, presence: true
  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user
  has_attached_file :photo, styles: { medium: '300x300>', thumb: '100x100>' },
                            default_url: '/images/:style/missing.png'
  validates_attachment_content_type :photo, content_type: %r{/\Aimage\/.*\Z/}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
  has_many :favorite_recipes
  has_many :favorites, through: :favorite_recipes, source: :recipe
  has_many :kitchens_users
  has_many :kitchens, through: :kitchens_users, source: :kitchen
  validates :name, :city, presence: true
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/food_types_controller.rb
class FoodTypesController < ApplicationController
  before_action :set_food_type, only: [:show]
  before_action :authenticate_user!, except: [:show]
  before_action :user_admin, except: [:show]
  respond_to :html
  def new
    @food_type = FoodType.new
  end

  def create
    @food_type = FoodType.create(food_type_params)
    respond_with @food_type
  end

  def show
    respond_with @food_type
  end

  private

  def user_admin
    unless current_user.admin?
      flash[:notice] = 'Você não pode criar Tipos de Comida'
      redirect_to root_path
    end
  end

  def set_food_type
    @food_type = FoodType.find(params[:id])
  end

  def food_type_params
    params.require(:food_type).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html
  def index
    @last_recipes = Recipe.first(20)
    @kitchens = Kitchen.all
    @food_types = FoodType.all
    @preferences = Preference.all
    @favorite_recipes = Recipe.order('favorite_count DESC').first(20)
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_action :set_kitchen, only: [:show]
  before_action :authenticate_user!, except: [:show]
  before_action :user_admin, except: [:show]
  respond_to :html
  def new
    @kitchen = Kitchen.new
  end

  def create
    @kitchen = Kitchen.create(kitchen_params)
    respond_with @kitchen
  end

  def show
    respond_with @kitchen
  end

  private

  def user_admin
    unless current_user.admin?
      flash[:notice] = 'Você não pode criar Cozinhas'
      redirect_to root_path
    end
  end

  def set_kitchen
    @kitchen = Kitchen.find(params[:id])
  end

  def kitchen_params
    params.require(:kitchen).permit(:name)
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: [:show]
  before_action :authenticate_user!, except: [:show]
  before_action :user_admin, except: [:show]
  respond_to :html
  def new
    @preference = Preference.new
  end

  def create
    @preference = Preference.create(preference_params)
    respond_with @preference
  end

  def show
    respond_with @preference
  end

  private

  def user_admin
    unless current_user.admin?
      flash[:notice] = 'Você não pode criar Preferências'
      redirect_to root_path
    end
  end

  def set_preference
    @preference = Preference.find(params[:id])
  end

  def preference_params
    params.require(:preference).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_collections, only: [:new, :create, :edit]
  before_action :set_recipe, only: [:edit, :show, :update, :destroy, :favorite]
  before_action :authenticate_user!, except: [:show]
  before_action :recipe_owner, only: [:edit, :update, :destroy]
  respond_to :html
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.create(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def show
    respond_with @recipe
  end

  def edit
    respond_with @recipe
  end

  def update
    @recipe.update(recipe_params)
    respond_with @recipe
  end

  def destroy
    @recipe.destroy
    respond_with @recipe
  end

  def favorite
    type = params[:type]
    if type == 'favorite'
      current_user.favorites << @recipe
      redirect_to :back, notice: 'You favorited #{@recipe.name}'

    elsif type == 'unfavorite'
      current_user.favorites.delete(@recipe)
      redirect_to :back, notice: 'Unfavorited #{@recipe.name}'

    else
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

  private

  def recipe_owner
    if current_user
      unless @recipe.user_id == current_user.id
        flash[:notice] = 'Você não pode editar receitas criadas por
                                                                outros usuários'
        redirect_to root_path
      end
    end
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_collections
    @kitchens = Kitchen.all
    @food_types = FoodType.all
    @preferences = Preference.all
  end

  def recipe_params
    params.require(:recipe)
          .permit(:name, :kitchen_id, :food_type_id, :preference_id, :servings,
                  :cook_time, :step_by_step, :ingredients,
                  :difficulty, :user_id, :photo)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :set_kitchens, only: [:edit, :update]

  def update
    kitchens_params[:kitchens].each do |kitchen|
      resource.kitchens << Kitchen.find(kitchen)
    end
    resource.save
    super
  end

  private

  def set_kitchens
    @kitchens = Kitchen.all
  end

  def sign_up_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :city)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :current_password,
                                 :city, :facebook, :twitter)
  end

  def kitchens_params
    params.require(:user).permit(kitchens: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :set_collections, only: [:show]

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_collections
    @kitchens = Kitchen.all
    @food_types = FoodType.all
    @preferences = Preference.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_types/_form.html.erb
<span class="error_message"><%= flash[:alert] %></span>
<%= form_for @food_type do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>

<p><%= f.submit submit_text %></p>
<% end %>

app/views/food_types/new.html.erb
<h1>Novo Tipo de Comida</h1>
<%= render partial: 'form', locals: {submit_text: 'Criar Tipo de Comida'}  %>

app/views/food_types/show.html.erb
<p><strong>Nome:</strong> <%= @food_type.name%></p>

<%= render @food_type.recipe %>

app/views/home/index.html.erb
<h1>Social Recipes</h1>
<h2>Últimas Receitas</h2>
<section id="last_recipes">
  <% @last_recipes.each do |recipe| %>
      <div class="last_recipes">
        <h3><%= link_to recipe.name, recipe %></h3>
        <p><%= image_tag recipe.photo.url(:medium) %><p>
        <p><%= recipe.preference.name %></p>
        <p><%= recipe.food_type.name %></p>
        <p><%= recipe.kitchen.name %></p>
        <p><%= recipe.difficulty %></p>
      </div>
      <hr>
  <% end %>
</section>
<h2>Preferidas dos usuários</h2>
<section id="favorite_recipes">
  <% @favorite_recipes.each do |recipe| %>
      <div class="favorite_recipes">
        <h3><%= link_to recipe.name, recipe %></h3>
        <p><%= image_tag recipe.photo.url(:medium) %><p>
        <p><%= recipe.preference.name %></p>
        <p><%= recipe.food_type.name %></p>
        <p><%= recipe.kitchen.name %></p>
        <p><%= recipe.difficulty %></p>
      </div>
      <hr>
  <% end %>
</section>
<aside>
  <h4>Cozinhas</h4>
  <% @kitchens.each do |kitchen| %>
    <p><%= link_to kitchen.name, kitchen %></p>
  <% end %>
</aside>
<hr>
<aside>
  <h4>Tipos</h4>
  <% @food_types.each do |food_type| %>
    <p><%= link_to food_type.name, food_type %></p>
  <% end %>
</aside>
<hr>
<aside>
<h4>Preferências</h4>
<% @preferences.each do |preference| %>
  <p><%= link_to preference.name, preference %></p>
<% end %>
</aside>

app/views/kitchens/_form.html.erb
<span class="error_message"><%= flash[:alert] %></span>
<%= form_for @kitchen do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>

<p><%= f.submit submit_text %></p>
<% end %>

app/views/kitchens/new.html.erb
<h1>Nova Cozinha</h1>
<%= render partial: 'form', locals: {submit_text: 'Criar Cozinha'}  %>

app/views/kitchens/show.html.erb
<p><strong>Nome:</strong> <%= @kitchen.name%></p>

<%= render @kitchen.recipe %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Receitas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/preferences/_form.html.erb
<span class="error_message"><%= flash[:alert] %></span>
<%= form_for @preference do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>

  <p><%= f.submit submit_text %></p>
<% end %>

app/views/preferences/new.html.erb
<h1>Nova Preferência</h1>
<hr>
<%= render partial: 'form', locals: { submit_text: 'Criar Preferência' } %>

app/views/preferences/show.html.erb
<p><strong>Nome:</strong> <%= @preference.name%></p>

<%= render @preference.recipe %>

app/views/recipes/_form.html.erb
<span class="error_message"><%= flash[:alert] %></span>
<%= form_for @recipe do |f| %>
  <p><%= f.file_field :photo %></p>

  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>

  <p><%= f.label :kitchen_id %></p>
  <p><%= f.collection_select :kitchen_id, @kitchens, :id, :name %></p>

  <p><%= f.label :food_type_id %></p>
  <p><%= f.collection_select :food_type_id, @food_types, :id, :name %></p>

  <p><%= f.label :preference_id %></p>
  <p><%= f.collection_select :preference_id, @preferences, :id, :name %></p>

  <p><%= f.label :servings %></p>
  <p><%= f.number_field :servings %></p>

  <p><%= f.label :cook_time %></p>
  <p><%= f.number_field :cook_time %></p>

  <p><%= f.label :difficulty %></p>
  <p><%= f.text_field :difficulty %></p>

  <p><%= f.label :ingredients %></p>
  <p><%= f.text_area :ingredients %></p>

  <p><%= f.label :step_by_step %></p>
  <p><%= f.text_area :step_by_step %></p>

  <p><%= f.submit submit_text %></p>
<% end %>

app/views/recipes/_recipe.html.erb
<h3>Receitas</h3>
<h3><%= link_to recipe.name, recipe %></h3>
<p><%= image_tag recipe.photo.url(:medium) %><p>
<p><%= recipe.preference.name %></p>
<p><%= recipe.food_type.name %></p>
<p><%= recipe.kitchen.name %></p>
<p><%= recipe.difficulty %></p>

app/views/recipes/edit.html.erb
<h1>Editar Receita</h1>
<hr>
<%= render partial: 'form', locals: {submit_text: 'Atualizar Receita'} %>

app/views/recipes/new.html.erb
<h1>Nova Receita</h1>
<hr>
<%= render partial: 'form', locals: { submit_text: 'Criar Receita' } %>

app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>
<hr>
<p><%= image_tag @recipe.photo.url(:medium) %><p>
<p><strong>Cozinha:</strong> <%= @recipe.kitchen.name%></p>
<p><strong>Tipo de comida:</strong> <%= @recipe.food_type.name %></p>
<p><strong>Preferência de Comida:</strong> <%= @recipe.preference.name %></p>
<p><strong>Serve:</strong> <%= @recipe.servings %></p>
<p><strong>Tempo de preparo:</strong> <%= @recipe.cook_time %></p>
<p><strong>Nível de Dificuldade:</strong> <%= @recipe.difficulty %></p>
<p><strong>Ingredientes:</strong> <%= @recipe.ingredients %></p>
<p><strong>Passo a Passo:</strong> <%= @recipe.step_by_step %></p>

<% if current_user %>
  <%=link_to 'Adicionar aos Favoritos', favorite_recipe_path(@recipe,
                                        type: 'favorite'), method: :put %>
  <%=link_to 'Remover dos Favoritos', favorite_recipe_path(@recipe,
                                        type: 'unfavorite'), method: :put %>
  <% if current_user.id == @recipe.user_id %>
    <p><%= link_to 'Deletar', @recipe,  method: :delete, data: { confirm:
                                        'Are you sure?' } %> </p>
    <p><%= link_to 'Editar', edit_recipe_path(@recipe) %></p>
<% end %>

<% end %>

app/views/users/show.html.erb
<div class="row">
  <aside class="">
  </aside>
  <section class="user_profile">
    <h1>Perfil de <%= @user.name %></h1>
    <p><span><%= @user.email %></span></p>
    <p><span><%= @user.city %></span></p>
    <% unless @user.facebook.nil? %>
      <p><span><%= link_to 'Facebook' , "https://www.facebook.com/#{@user.facebook}", target: '_blank' %></span></p>
    <% end %>
    <% unless @user.twitter.nil? %>
      <p><span><%= link_to 'Twitter' , "https://www.twitter.com/#{@user.twitter}", target: '_blank' %></span></p>
    <% end %>
<hr>
    <h2>Receitas de <%= @user.name %></h2>
    <%= render @user.recipes %>
  </section>
</div>
<aside>
  <h4>Cozinhas</h4>
  <% @kitchens.each do |kitchen| %>
    <p><%= link_to kitchen.name, kitchen %></p>
  <% end %>
</aside>
<hr>
<aside>
  <h4>Tipos</h4>
  <% @food_types.each do |food_type| %>
    <p><%= link_to food_type.name, food_type %></p>
  <% end %>
</aside>
<hr>
<aside>
<h4>Preferências</h4>
<% @preferences.each do |preference| %>
  <p><%= link_to preference.name, preference %></p>
<% end %>
</aside>